- name: Install Flatpak apps
  community.general.flatpak:
    name: "{{ flatpak_apps }}"
    state: present
  loop:
    - app.zen_browser.zen
    - io.missioncenter.MissionCenter
    - com.bitwarden.desktop
  loop_control:
    loop_var: flatpak_apps
  tags:
    - apps
    - flatpak apps

- name: Add third party repositories
  tags:
    - apps
    - os_repo_apps
  block:
    - name: Add COPR
      become: true
      community.general.copr:
        name: "{{ copr_repo }}"
        state: enabled
      loop:
        - pgdev/ghostty
      loop_control:
        loop_var: copr_repo

    - name: Import GPG keys
      ansible.builtin.rpm_key:
        state: present
        key: "{{ key_url }}"
      loop:
        - https://packages.microsoft.com/keys/microsoft.asc
      loop_control:
        loop_var: key_url

    - name: Add yum repositories
      become: true
      ansible.builtin.yum_repository:
        name: "{{ repo_item.name }}"
        description: "{{ repo_item.description }}"
        baseurl: "{{ repo_item.baseurl }}"
        enabled: "{{ repo_item.enabled | default(true) }}"
        gpgcheck: "{{ repo_item.gpgcheck | default(true) }}"
        gpgkey: "{{ repo_item.gpgkey | default(omit) }}"
        state: "{{ repo_item.state | default('present') }}"
      loop:
        - name: code
          description: Visual Studio Code
          baseurl: https://packages.microsoft.com/yumrepos/vscode
          gpgkey: https://packages.microsoft.com/keys/microsoft.asc
          state: absent
      loop_control:
        loop_var: repo_item

- name: Install dnf packages
  tags:
    - apps
    - os_apps
  block:
    - name: Ensure dnf is up to date
      ansible.builtin.dnf:
        update_cache: true
      become: true

    - name: Install dnf packages
      become: true
      ansible.builtin.package:
        name:
          - git
          - htop
          - jq
          - ghostty
          - code
          - stow
          - neovim
        state: present
